"""Governed deterministic production rules for the operations domain."""

from __future__ import annotations

from decimal import Decimal

from pharma_api.domain.diagnostics.actions import ACTION_BY_CODE
from pharma_api.domain.diagnostics.conditions import (
    AbsChange,
    AllOf,
    Compare,
    Condition,
    Fixed,
    Kpi,
    NetworkAverage,
    Persisted,
    Severity,
)
from pharma_api.domain.diagnostics.engine_contracts import (
    ActionReference,
    EvidenceDirection,
    EvidenceSpec,
    EvidenceType,
    HypothesisSpec,
)
from pharma_api.domain.diagnostics.rules.definitions import GovernedRuleDefinition

_OWNER = "data-operations"
_COMMON_LIMITATIONS = (
    "The rule reports an observed analytical signal and does not prove root cause.",
    (
        "Credential, reprocessing, deletion or data-correction decisions require authorized "
        "human review."
    ),
)


def _action(code: str, rationale: str) -> ActionReference:
    definition = ACTION_BY_CODE[code]
    return ActionReference(
        action_code=definition.code,
        action_version=definition.version,
        rationale=rationale,
        suggested_priority=definition.default_priority,
    )


def _evidence(
    *,
    code: str,
    kpi: str,
    observation_key: str,
    evidence_type: EvidenceType,
    direction: EvidenceDirection,
    detail: str,
    reference_key: str | None = None,
) -> EvidenceSpec:
    return EvidenceSpec(
        evidence_code=code,
        evidence_type=evidence_type,
        kpi_code=kpi,
        observation_key=observation_key,
        reference_key=reference_key,
        direction=direction,
        relation="supports",
        weight=Decimal("1"),
        detail=detail,
    )


def _hypothesis(code: str, evidence_code: str, explanation: str) -> HypothesisSpec:
    return HypothesisSpec(
        hypothesis_code=code,
        explanation=explanation,
        supporting_evidence_codes=(evidence_code,),
        logic_version="operations-v1",
        minimum_support=Decimal("0.5000"),
    )


def _rule(
    *,
    code: str,
    title: str,
    objective: str,
    summary: str,
    severity: Severity,
    primary_kpi: str,
    condition: Condition,
    action_code: str,
    action_rationale: str,
    evidence_code: str,
    evidence_type: EvidenceType,
    evidence_direction: EvidenceDirection,
    evidence_detail: str,
    hypothesis_code: str,
    hypothesis: str,
    expected_impact: str,
    dimensions: tuple[str, ...],
    evaluation_window: str,
    observation_key: str | None = None,
    reference_key: str | None = None,
    limitations: tuple[str, ...] = _COMMON_LIMITATIONS,
) -> GovernedRuleDefinition:
    return GovernedRuleDefinition(
        code=code,
        version=1,
        title=title,
        objective=objective,
        summary=summary,
        domain="operations",
        base_severity=severity,
        primary_kpi_code=primary_kpi,
        condition=condition,
        actions=(_action(action_code, action_rationale),),
        evidence=(
            _evidence(
                code=evidence_code,
                kpi=primary_kpi,
                observation_key=observation_key or primary_kpi,
                evidence_type=evidence_type,
                direction=evidence_direction,
                detail=evidence_detail,
                reference_key=reference_key,
            ),
        ),
        hypotheses=(_hypothesis(hypothesis_code, evidence_code, hypothesis),),
        dimensions=dimensions,
        evaluation_window=evaluation_window,
        expected_impact=expected_impact,
        limitations=limitations,
        owner=_OWNER,
        change_note="Initial governed operations production rule.",
    )


_CURRENT_WINDOW = "current analytical period"
_PREVIOUS_WINDOW = "current analytical period versus the previous comparable period"
_NETWORK_WINDOW = "current analytical period versus the authorized network average"
_PERSISTENCE_WINDOW = "current analytical frame plus two previous frames"

OPERATIONS_RULES: tuple[GovernedRuleDefinition, ...] = tuple(
    sorted(
        (
            _rule(
                code="operations.completeness_below_network",
                title="Completude abaixo da rede",
                objective="Comparar a completude local à média governada da rede.",
                summary="A completude está abaixo da média da rede.",
                severity="high",
                primary_kpi="operations.completeness",
                condition=Compare(
                    Kpi("operations.completeness"),
                    "lt",
                    NetworkAverage("operations.completeness"),
                ),
                action_code="operations.quality_incident_review",
                action_rationale=(
                    "Revisar escopo e qualidade sem reprocessar dados automaticamente."
                ),
                evidence_code="operations.completeness_network_gap",
                evidence_type="comparison",
                evidence_direction="below",
                evidence_detail="Completude local comparada à média autorizada da rede.",
                hypothesis_code="operations.local_completeness_gap",
                hypothesis="Origem, mapeamento ou processamento podem explicar o desvio.",
                expected_impact="Direcionar revisão de qualidade com rastreabilidade.",
                dimensions=("tenant", "company", "branch"),
                evaluation_window=_NETWORK_WINDOW,
                reference_key="network_average:operations.completeness",
            ),
            _rule(
                code="operations.completeness_decline",
                title="Queda da completude",
                objective="Detectar queda direcional da completude frente ao período anterior.",
                summary="A completude caiu no escopo avaliado.",
                severity="high",
                primary_kpi="operations.completeness",
                condition=Compare(
                    AbsChange(
                        "operations.completeness",
                        baseline="previous",
                    ),
                    "lt",
                    Fixed(Decimal("0")),
                ),
                action_code="operations.quality_incident_review",
                action_rationale="Revisar origem e processamento sem reprocessamento automático.",
                evidence_code="operations.completeness_decline_signal",
                evidence_type="comparison",
                evidence_direction="decreasing",
                evidence_detail="Completude atual comparada ao período anterior equivalente.",
                hypothesis_code="operations.completeness_deterioration",
                hypothesis="Origem, mapeamento ou processamento podem explicar a queda.",
                expected_impact="Conter deterioração da qualidade de dados.",
                dimensions=("tenant", "company", "branch"),
                evaluation_window=_PREVIOUS_WINDOW,
                reference_key="previous:operations.completeness",
            ),
            _rule(
                code="operations.consistency_below_network",
                title="Consistência abaixo da rede",
                objective="Comparar a consistência local à média governada da rede.",
                summary="A consistência está abaixo da média da rede.",
                severity="high",
                primary_kpi="operations.consistency",
                condition=Compare(
                    Kpi("operations.consistency"),
                    "lt",
                    NetworkAverage("operations.consistency"),
                ),
                action_code="operations.quality_incident_review",
                action_rationale="Revisar regras e registros sem correção automática.",
                evidence_code="operations.consistency_network_gap",
                evidence_type="comparison",
                evidence_direction="below",
                evidence_detail="Consistência local comparada à média autorizada da rede.",
                hypothesis_code="operations.local_consistency_gap",
                hypothesis="Mapeamento, origem ou regra de qualidade podem explicar o desvio.",
                expected_impact="Priorizar revisão de consistência.",
                dimensions=("tenant", "company", "branch"),
                evaluation_window=_NETWORK_WINDOW,
                reference_key="network_average:operations.consistency",
            ),
            _rule(
                code="operations.consistency_decline",
                title="Queda da consistência",
                objective="Detectar queda direcional da consistência frente ao período anterior.",
                summary="A consistência caiu no escopo avaliado.",
                severity="high",
                primary_kpi="operations.consistency",
                condition=Compare(
                    AbsChange(
                        "operations.consistency",
                        baseline="previous",
                    ),
                    "lt",
                    Fixed(Decimal("0")),
                ),
                action_code="operations.quality_incident_review",
                action_rationale="Revisar regras e registros sem correção automática.",
                evidence_code="operations.consistency_decline_signal",
                evidence_type="comparison",
                evidence_direction="decreasing",
                evidence_detail="Consistência atual comparada ao período anterior equivalente.",
                hypothesis_code="operations.consistency_deterioration",
                hypothesis="Mapeamento, origem ou regra de qualidade podem explicar a queda.",
                expected_impact="Conter deterioração da consistência.",
                dimensions=("tenant", "company", "branch"),
                evaluation_window=_PREVIOUS_WINDOW,
                reference_key="previous:operations.consistency",
            ),
            _rule(
                code="operations.data_freshness_above_network",
                title="Freshness acima da rede",
                objective="Comparar o atraso de freshness à média governada da rede.",
                summary="O atraso de freshness supera a média da rede.",
                severity="high",
                primary_kpi="operations.data_freshness",
                condition=Compare(
                    Kpi("operations.data_freshness"),
                    "gt",
                    NetworkAverage("operations.data_freshness"),
                ),
                action_code="operations.freshness_recovery",
                action_rationale="Revisar pipeline sem disparar reprocessamento automático.",
                evidence_code="operations.data_freshness_network_gap",
                evidence_type="comparison",
                evidence_direction="above",
                evidence_detail="Freshness em segundos comparada à média autorizada da rede.",
                hypothesis_code="operations.local_freshness_gap",
                hypothesis="Origem, fila ou processamento podem explicar o desvio.",
                expected_impact="Direcionar recuperação com decisão humana.",
                dimensions=("tenant", "company", "branch"),
                evaluation_window=_NETWORK_WINDOW,
                reference_key="network_average:operations.data_freshness",
            ),
            _rule(
                code="operations.data_freshness_increase",
                title="Aumento do atraso de freshness",
                objective="Detectar aumento direcional do atraso de freshness.",
                summary="O atraso de freshness aumentou no escopo avaliado.",
                severity="high",
                primary_kpi="operations.data_freshness",
                condition=Compare(
                    AbsChange(
                        "operations.data_freshness",
                        baseline="previous",
                    ),
                    "gt",
                    Fixed(Decimal("0")),
                ),
                action_code="operations.freshness_recovery",
                action_rationale="Revisar pipeline sem disparar reprocessamento automático.",
                evidence_code="operations.data_freshness_increase_signal",
                evidence_type="comparison",
                evidence_direction="increasing",
                evidence_detail="Freshness atual comparada ao período anterior equivalente.",
                hypothesis_code="operations.freshness_deterioration",
                hypothesis="Origem, fila ou processamento podem explicar o aumento.",
                expected_impact="Conter deterioração de atualidade dos dados.",
                dimensions=("tenant", "company", "branch"),
                evaluation_window=_PREVIOUS_WINDOW,
                reference_key="previous:operations.data_freshness",
            ),
            _rule(
                code="operations.duplicate_rate_above_network",
                title="Duplicidade acima da rede",
                objective="Comparar a taxa de duplicidade à média governada da rede.",
                summary="A taxa de duplicidade supera a média da rede.",
                severity="high",
                primary_kpi="operations.duplicate_rate",
                condition=Compare(
                    Kpi("operations.duplicate_rate"),
                    "gt",
                    NetworkAverage("operations.duplicate_rate"),
                ),
                action_code="operations.duplicate_cleanup",
                action_rationale=(
                    "Revisar registros e chave de idempotência sem excluir dados automaticamente."
                ),
                evidence_code="operations.duplicate_rate_network_gap",
                evidence_type="comparison",
                evidence_direction="above",
                evidence_detail="Taxa de duplicidade comparada à média autorizada da rede.",
                hypothesis_code="operations.local_duplicate_gap",
                hypothesis="Origem, chave ou repetição de carga podem explicar o desvio.",
                expected_impact="Direcionar saneamento com revisão humana.",
                dimensions=("tenant", "company", "branch"),
                evaluation_window=_NETWORK_WINDOW,
                reference_key="network_average:operations.duplicate_rate",
            ),
            _rule(
                code="operations.duplicate_rate_increase",
                title="Aumento da duplicidade",
                objective="Detectar aumento direcional da taxa de duplicidade.",
                summary="A taxa de duplicidade aumentou no escopo avaliado.",
                severity="high",
                primary_kpi="operations.duplicate_rate",
                condition=Compare(
                    AbsChange(
                        "operations.duplicate_rate",
                        baseline="previous",
                    ),
                    "gt",
                    Fixed(Decimal("0")),
                ),
                action_code="operations.duplicate_cleanup",
                action_rationale="Revisar registros sem excluir dados automaticamente.",
                evidence_code="operations.duplicate_rate_increase_signal",
                evidence_type="comparison",
                evidence_direction="increasing",
                evidence_detail=(
                    "Taxa de duplicidade atual comparada ao período anterior equivalente."
                ),
                hypothesis_code="operations.duplicate_deterioration",
                hypothesis="Origem, chave ou repetição de carga podem explicar o aumento.",
                expected_impact="Conter deterioração de duplicidade.",
                dimensions=("tenant", "company", "branch"),
                evaluation_window=_PREVIOUS_WINDOW,
                reference_key="previous:operations.duplicate_rate",
            ),
            _rule(
                code="operations.duplicate_rate_positive",
                title="Ocorrência de duplicidade",
                objective="Detectar taxa de duplicidade acima da fronteira de zero.",
                summary="Existem registros duplicados no escopo avaliado.",
                severity="medium",
                primary_kpi="operations.duplicate_rate",
                condition=Compare(
                    Kpi("operations.duplicate_rate"),
                    "gt",
                    Fixed(Decimal("0")),
                ),
                action_code="operations.duplicate_cleanup",
                action_rationale="Classificar duplicidades sem excluir registros automaticamente.",
                evidence_code="operations.duplicate_rate_positive_signal",
                evidence_type="threshold",
                evidence_direction="above",
                evidence_detail="Taxa de duplicidade observada acima de zero.",
                hypothesis_code="operations.duplicate_event_context",
                hypothesis="Origem, chave ou repetição de carga podem estar associados ao evento.",
                expected_impact="Dar visibilidade à duplicidade sem presumir causa.",
                dimensions=("tenant", "company", "branch"),
                evaluation_window=_CURRENT_WINDOW,
            ),
            _rule(
                code="operations.failed_batches_increase",
                title="Aumento de lotes falhos",
                objective="Detectar aumento direcional da quantidade de lotes falhos.",
                summary="A quantidade de lotes falhos aumentou.",
                severity="critical",
                primary_kpi="operations.failed_batches",
                condition=Compare(
                    AbsChange(
                        "operations.failed_batches",
                        baseline="previous",
                    ),
                    "gt",
                    Fixed(Decimal("0")),
                ),
                action_code="operations.integration_check",
                action_rationale="Revisar lotes e integração sem reprocessar automaticamente.",
                evidence_code="operations.failed_batches_increase_signal",
                evidence_type="comparison",
                evidence_direction="increasing",
                evidence_detail="Lotes falhos atuais comparados ao período anterior equivalente.",
                hypothesis_code="operations.batch_failure_deterioration",
                hypothesis="Origem, integração ou processamento podem explicar o aumento.",
                expected_impact="Conter deterioração de processamento.",
                dimensions=("tenant", "company", "branch"),
                evaluation_window=_PREVIOUS_WINDOW,
                reference_key="previous:operations.failed_batches",
            ),
            _rule(
                code="operations.failed_batches_persistent_positive",
                title="Lotes falhos recorrentes",
                objective="Detectar lotes falhos no frame atual e em dois frames anteriores.",
                summary=(
                    "Lotes falhos permanecem presentes no período atual e no histórico exigido."
                ),
                severity="critical",
                primary_kpi="operations.failed_batches",
                condition=AllOf(
                    nodes=(
                        Compare(
                            Kpi("operations.failed_batches"),
                            "gt",
                            Fixed(Decimal("0")),
                        ),
                        Persisted(
                            Compare(
                                Kpi("operations.failed_batches"),
                                "gt",
                                Fixed(Decimal("0")),
                            ),
                            periods=2,
                        ),
                    ),
                ),
                action_code="operations.integration_check",
                action_rationale="Escalar revisão da recorrência sem reprocessar automaticamente.",
                evidence_code="operations.failed_batches_persistent_signal",
                evidence_type="threshold",
                evidence_direction="above",
                evidence_detail=(
                    "Contagem atual positiva; persistência histórica comprovada pelo trace."
                ),
                hypothesis_code="operations.unresolved_batch_failure",
                hypothesis=(
                    "Restrição ainda não resolvida de origem, integração ou processamento pode "
                    "explicar a recorrência."
                ),
                expected_impact="Distinguir falha recorrente de evento isolado.",
                dimensions=("tenant", "company", "branch"),
                evaluation_window=_PERSISTENCE_WINDOW,
            ),
            _rule(
                code="operations.failed_batches_positive",
                title="Ocorrência de lote falho",
                objective="Detectar quantidade positiva de lotes falhos.",
                summary="Existe lote falho no escopo avaliado.",
                severity="critical",
                primary_kpi="operations.failed_batches",
                condition=Compare(
                    Kpi("operations.failed_batches"),
                    "gt",
                    Fixed(Decimal("0")),
                ),
                action_code="operations.integration_check",
                action_rationale="Classificar a falha sem reprocessar automaticamente.",
                evidence_code="operations.failed_batches_positive_signal",
                evidence_type="threshold",
                evidence_direction="above",
                evidence_detail="Contagem de lotes falhos acima de zero.",
                hypothesis_code="operations.batch_failure_context",
                hypothesis="Origem, integração ou processamento podem estar associados ao evento.",
                expected_impact="Dar visibilidade à falha com revisão humana.",
                dimensions=("tenant", "company", "branch"),
                evaluation_window=_CURRENT_WINDOW,
            ),
            _rule(
                code="operations.ingestion_duration_increase",
                title="Aumento da duração da ingestão",
                objective="Detectar aumento direcional da duração de ingestão.",
                summary="A duração de ingestão aumentou no escopo avaliado.",
                severity="medium",
                primary_kpi="operations.ingestion_duration",
                condition=Compare(
                    AbsChange(
                        "operations.ingestion_duration",
                        baseline="previous",
                    ),
                    "gt",
                    Fixed(Decimal("0")),
                ),
                action_code="operations.freshness_recovery",
                action_rationale="Revisar pipeline sem executar recomputação automática.",
                evidence_code="operations.ingestion_duration_increase_signal",
                evidence_type="comparison",
                evidence_direction="increasing",
                evidence_detail="Duração atual comparada ao período anterior equivalente.",
                hypothesis_code="operations.ingestion_duration_pressure",
                hypothesis="Origem, volume ou processamento podem explicar o aumento.",
                expected_impact="Antecipar deterioração operacional sem inventar SLA.",
                dimensions=("tenant", "company", "branch"),
                evaluation_window=_PREVIOUS_WINDOW,
                reference_key="previous:operations.ingestion_duration",
            ),
            _rule(
                code="operations.integration_availability_decline",
                title="Queda da disponibilidade de integração",
                objective="Detectar queda direcional da disponibilidade de integração.",
                summary="A disponibilidade de integração caiu.",
                severity="critical",
                primary_kpi="operations.integration_availability",
                condition=Compare(
                    AbsChange(
                        "operations.integration_availability",
                        baseline="previous",
                    ),
                    "lt",
                    Fixed(Decimal("0")),
                ),
                action_code="operations.integration_check",
                action_rationale=(
                    "Revisar integração sem alterar credenciais ou reprocessar automaticamente."
                ),
                evidence_code="operations.integration_availability_decline_signal",
                evidence_type="comparison",
                evidence_direction="decreasing",
                evidence_detail="Disponibilidade atual comparada ao período anterior equivalente.",
                hypothesis_code="operations.integration_availability_deterioration",
                hypothesis="Origem, conectividade ou processamento podem explicar a queda.",
                expected_impact="Conter deterioração da disponibilidade.",
                dimensions=("tenant", "company", "branch"),
                evaluation_window=_PREVIOUS_WINDOW,
                reference_key="previous:operations.integration_availability",
            ),
            _rule(
                code="operations.integration_availability_zero",
                title="Integração indisponível no período",
                objective="Detectar disponibilidade observada igual a zero.",
                summary="A disponibilidade de integração observada é zero.",
                severity="critical",
                primary_kpi="operations.integration_availability",
                condition=Compare(
                    Kpi("operations.integration_availability"),
                    "eq",
                    Fixed(Decimal("0")),
                ),
                action_code="operations.integration_check",
                action_rationale=(
                    "Verificar integração sem alterar credenciais ou reprocessar automaticamente."
                ),
                evidence_code="operations.integration_availability_zero_signal",
                evidence_type="threshold",
                evidence_direction="equal",
                evidence_detail="Disponibilidade observada exatamente na fronteira de zero.",
                hypothesis_code="operations.integration_unavailability_context",
                hypothesis=(
                    "Conectividade, credencial, origem ou processamento podem explicar o sinal."
                ),
                expected_impact="Priorizar verificação sem presumir causa.",
                dimensions=("tenant", "company", "branch"),
                evaluation_window=_CURRENT_WINDOW,
            ),
            _rule(
                code="operations.quality_incidents_positive",
                title="Ocorrência de incidente de qualidade",
                objective="Detectar contagem positiva de incidentes de qualidade.",
                summary="Existe incidente de qualidade no escopo avaliado.",
                severity="high",
                primary_kpi="operations.quality_incidents",
                condition=Compare(
                    Kpi("operations.quality_incidents"),
                    "gt",
                    Fixed(Decimal("0")),
                ),
                action_code="operations.quality_incident_review",
                action_rationale=(
                    "Classificar o incidente sem corrigir ou excluir dados automaticamente."
                ),
                evidence_code="operations.quality_incidents_positive_signal",
                evidence_type="threshold",
                evidence_direction="above",
                evidence_detail="Contagem de incidentes de qualidade acima de zero.",
                hypothesis_code="operations.quality_incident_context",
                hypothesis="Origem, regra ou processamento podem estar associados ao incidente.",
                expected_impact="Dar visibilidade ao incidente com revisão rastreável.",
                dimensions=("tenant", "company", "branch"),
                evaluation_window=_CURRENT_WINDOW,
            ),
            _rule(
                code="operations.rejection_rate_above_network",
                title="Rejeições acima da rede",
                objective="Comparar a taxa de rejeição à média governada da rede.",
                summary="A taxa de rejeição supera a média da rede.",
                severity="high",
                primary_kpi="operations.rejection_rate",
                condition=Compare(
                    Kpi("operations.rejection_rate"),
                    "gt",
                    NetworkAverage("operations.rejection_rate"),
                ),
                action_code="operations.rejection_triage",
                action_rationale="Revisar registros rejeitados sem reprocessar automaticamente.",
                evidence_code="operations.rejection_rate_network_gap",
                evidence_type="comparison",
                evidence_direction="above",
                evidence_detail="Taxa de rejeição comparada à média autorizada da rede.",
                hypothesis_code="operations.local_rejection_gap",
                hypothesis="Origem, mapeamento ou validação podem explicar o desvio.",
                expected_impact="Direcionar triagem de rejeições.",
                dimensions=("tenant", "company", "branch"),
                evaluation_window=_NETWORK_WINDOW,
                reference_key="network_average:operations.rejection_rate",
            ),
            _rule(
                code="operations.rejection_rate_increase",
                title="Aumento da taxa de rejeição",
                objective="Detectar aumento direcional da taxa de rejeição.",
                summary="A taxa de rejeição aumentou.",
                severity="high",
                primary_kpi="operations.rejection_rate",
                condition=Compare(
                    AbsChange(
                        "operations.rejection_rate",
                        baseline="previous",
                    ),
                    "gt",
                    Fixed(Decimal("0")),
                ),
                action_code="operations.rejection_triage",
                action_rationale="Revisar registros rejeitados sem reprocessar automaticamente.",
                evidence_code="operations.rejection_rate_increase_signal",
                evidence_type="comparison",
                evidence_direction="increasing",
                evidence_detail="Taxa de rejeição atual comparada ao período anterior equivalente.",
                hypothesis_code="operations.rejection_deterioration",
                hypothesis="Origem, mapeamento ou validação podem explicar o aumento.",
                expected_impact="Conter deterioração de rejeições.",
                dimensions=("tenant", "company", "branch"),
                evaluation_window=_PREVIOUS_WINDOW,
                reference_key="previous:operations.rejection_rate",
            ),
            _rule(
                code="operations.rejection_rate_positive",
                title="Ocorrência de rejeição",
                objective="Detectar taxa de rejeição acima da fronteira de zero.",
                summary="Existem registros rejeitados no escopo avaliado.",
                severity="medium",
                primary_kpi="operations.rejection_rate",
                condition=Compare(
                    Kpi("operations.rejection_rate"),
                    "gt",
                    Fixed(Decimal("0")),
                ),
                action_code="operations.rejection_triage",
                action_rationale="Classificar rejeições sem reprocessar automaticamente.",
                evidence_code="operations.rejection_rate_positive_signal",
                evidence_type="threshold",
                evidence_direction="above",
                evidence_detail="Taxa de rejeição observada acima de zero.",
                hypothesis_code="operations.rejection_event_context",
                hypothesis="Origem, mapeamento ou validação podem estar associados ao evento.",
                expected_impact="Dar visibilidade à rejeição sem presumir causa.",
                dimensions=("tenant", "company", "branch"),
                evaluation_window=_CURRENT_WINDOW,
            ),
            _rule(
                code="operations.source_lag_increase",
                title="Aumento do atraso da fonte",
                objective="Detectar aumento direcional do atraso entre fonte e plataforma.",
                summary="O atraso da fonte aumentou no escopo avaliado.",
                severity="high",
                primary_kpi="operations.source_lag",
                condition=Compare(
                    AbsChange(
                        "operations.source_lag",
                        baseline="previous",
                    ),
                    "gt",
                    Fixed(Decimal("0")),
                ),
                action_code="operations.freshness_recovery",
                action_rationale="Revisar origem e pipeline sem reprocessar automaticamente.",
                evidence_code="operations.source_lag_increase_signal",
                evidence_type="comparison",
                evidence_direction="increasing",
                evidence_detail="Atraso da fonte atual comparado ao período anterior equivalente.",
                hypothesis_code="operations.source_lag_deterioration",
                hypothesis="Origem, conectividade ou fila podem explicar o aumento.",
                expected_impact="Conter atraso sem inventar SLA fixo.",
                dimensions=("tenant", "company", "branch"),
                evaluation_window=_PREVIOUS_WINDOW,
                reference_key="previous:operations.source_lag",
            ),
        ),
        key=lambda rule: rule.code,
    )
)
