"""Deterministic diagnostics domain primitives."""

from pharma_api.domain.diagnostics.actions import (
    ACTION_BY_CODE,
    ACTION_CATALOG,
    ActionDefinition,
    validate_action_catalog,
)
from pharma_api.domain.diagnostics.conditions import (
    DEFAULT_RULE_CONTROLS,
    Condition,
    ConditionValidationError,
    RuleControls,
    condition_kpi_dependencies,
    evaluate_predicate,
    parse_condition,
    parse_rule_controls,
    serialize_condition,
    serialize_rule_controls,
    validate_condition,
)
from pharma_api.domain.diagnostics.engine import (
    ActionReference,
    CanonicalizationError,
    DiagnosticEngineValidationError,
    EvaluationResult,
    EvaluationScope,
    EvidenceSpec,
    HypothesisSpec,
    KPIObservation,
    ObservationFrame,
    RuleEvaluationInput,
    RuleSnapshot,
    canonical_json,
    canonical_sha256,
    evaluate_rule,
)

__all__ = [
    "ACTION_BY_CODE",
    "ACTION_CATALOG",
    "DEFAULT_RULE_CONTROLS",
    "ActionDefinition",
    "ActionReference",
    "CanonicalizationError",
    "Condition",
    "ConditionValidationError",
    "DiagnosticEngineValidationError",
    "EvaluationResult",
    "EvaluationScope",
    "EvidenceSpec",
    "HypothesisSpec",
    "KPIObservation",
    "ObservationFrame",
    "RuleControls",
    "RuleEvaluationInput",
    "RuleSnapshot",
    "canonical_json",
    "canonical_sha256",
    "condition_kpi_dependencies",
    "evaluate_predicate",
    "evaluate_rule",
    "parse_condition",
    "parse_rule_controls",
    "serialize_condition",
    "serialize_rule_controls",
    "validate_action_catalog",
    "validate_condition",
]
