# ruff: noqa: E501
"""Frozen deterministic action catalog payload for migration 20260719_0005.

This module intentionally uses only the Python standard library. Historical
migrations can import it without importing the live diagnostics domain catalog.
"""

from __future__ import annotations

import json
from collections.abc import Iterator, Mapping
from hashlib import sha256
from typing import Any, cast
from uuid import NAMESPACE_URL, UUID, uuid5

CATALOG_VERSION = 1
SOURCE_REVISION = "55a5ec43991c4380036a6a6799fecc403cf68120"
CANONICAL_JSON_OPTIONS: Mapping[str, object] = {
    "ensure_ascii": False,
    "separators": (",", ":"),
    "sort_keys": True,
}

ACTION_CATALOG_DEFINITIONS: tuple[dict[str, object], ...] = (
    {
        "code": "inventory.emergency_restock",
        "title": "Reposição emergencial de ruptura",
        "description": "Preparar uma recomendação de reposição emergencial para produtos em ruptura "
        "recorrente.",
        "justification": "Ruptura em produtos de giro compromete receita e fidelidade do cliente.",
        "domain": "inventory",
        "default_priority": 1,
        "suggested_role": "branch_manager",
        "suggested_deadline_days": 2,
        "preconditions": ["Produto com histórico de venda no período."],
        "steps": [
            "Confirmar ruptura física no estoque da filial.",
            "Selecionar fornecedor com menor lead time para os itens.",
            "Gerar uma minuta de pedido com quantidade e custo estimados, sem transmissão "
            "automática.",
            "Submeter a minuta ao fluxo humano de aprovação e registrar a decisão tomada.",
        ],
        "risk": "Custo de compra emergencial acima do negociado.",
        "expected_impact": "Recuperação da disponibilidade e da receita perdida por ruptura.",
        "tracking_kpi": "inventory.zero_stock_rate",
        "success_criteria": "Taxa de ruptura dos itens tratados volta à média da rede em 7 dias.",
        "closure_criteria": "Decisão registrada; quando aprovada fora do motor, recebimento acompanhado "
        "e estoque regularizado.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
    {
        "code": "inventory.coverage_review",
        "title": "Revisão de cobertura de estoque",
        "description": "Recalcular parâmetros de cobertura dos produtos fora da faixa-alvo.",
        "justification": "Cobertura excessiva imobiliza capital; cobertura baixa gera ruptura.",
        "domain": "inventory",
        "default_priority": 2,
        "suggested_role": "analyst",
        "suggested_deadline_days": 5,
        "preconditions": [],
        "steps": [
            "Listar produtos fora da faixa de cobertura-alvo.",
            "Revisar demanda média e lead time parametrizados.",
            "Ajustar estoque mínimo e ponto de pedido.",
            "Monitorar a cobertura na semana seguinte.",
        ],
        "risk": "Ajuste incorreto de parâmetros pode gerar excesso ou ruptura.",
        "expected_impact": "Cobertura em dias dentro da faixa-alvo da categoria.",
        "tracking_kpi": "inventory.coverage_days",
        "success_criteria": "Cobertura mediana da categoria dentro da faixa-alvo por 14 dias.",
        "closure_criteria": "Parâmetros revisados e cobertura estabilizada na faixa-alvo.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
    {
        "code": "inventory.branch_transfer",
        "title": "Transferência entre filiais",
        "description": "Transferir excedente de filiais com excesso para filiais em ruptura.",
        "justification": "Rebalancear estoque entre filiais evita compra desnecessária e perda.",
        "domain": "inventory",
        "default_priority": 2,
        "suggested_role": "company_admin",
        "suggested_deadline_days": 3,
        "preconditions": [],
        "steps": [
            "Identificar filiais doadoras com excesso do produto.",
            "Confirmar necessidade e capacidade da filial receptora.",
            "Emitir ordem de transferência e agendar logística.",
            "Confirmar entrada do estoque na filial receptora.",
        ],
        "risk": "Custo logístico da transferência e risco de avaria no transporte.",
        "expected_impact": "Redução simultânea de excesso e ruptura sem nova compra.",
        "tracking_kpi": "inventory.excess_count",
        "success_criteria": "Excesso e ruptura do produto reduzidos nas duas filiais em 7 dias.",
        "closure_criteria": "Transferência concluída e saldos regularizados nas duas filiais.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
    {
        "code": "inventory.expiring_quarantine",
        "title": "Quarentena de lotes próximos ao vencimento",
        "description": "Isolar lotes próximos do vencimento e definir ação de escoamento.",
        "justification": "Venda de produto vencido gera risco sanitário, devolução e multa.",
        "domain": "inventory",
        "default_priority": 1,
        "suggested_role": "branch_manager",
        "suggested_deadline_days": 1,
        "preconditions": [],
        "steps": [
            "Bloquear os lotes no sistema e sinalizar fisicamente.",
            "Avaliar devolução ao fornecedor dentro do prazo contratual.",
            "Definir promoção de escoamento para lotes ainda vendáveis.",
            "Registrar o destino final de cada lote.",
        ],
        "risk": "Perda financeira dos lotes sem escoamento possível.",
        "expected_impact": "Eliminação do risco de venda de produto vencido.",
        "tracking_kpi": "inventory.expiring_lots",
        "success_criteria": "Nenhum lote vencido disponível para venda após a quarentena.",
        "closure_criteria": "Todos os lotes com destino registrado e estoque vencido zerado.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
    {
        "code": "inventory.audit_count",
        "title": "Auditoria de inventário por contagem",
        "description": "Executar contagem cíclica nos itens com divergência de estoque.",
        "justification": "Divergência entre estoque físico e sistêmico distorce KPIs e compras.",
        "domain": "inventory",
        "default_priority": 3,
        "suggested_role": "branch_manager",
        "suggested_deadline_days": 7,
        "preconditions": [],
        "steps": [
            "Bloquear movimentação dos itens selecionados.",
            "Executar contagem física com dupla conferência.",
            "Lançar ajustes com justificativa e aprovação.",
            "Investigar a causa raiz da divergência.",
        ],
        "risk": "Parada temporária da movimentação dos itens auditados.",
        "expected_impact": "Acuracidade de estoque restaurada e ajustes rastreáveis.",
        "tracking_kpi": "inventory.negative_stock_count",
        "success_criteria": "Divergências ajustadas e sem reincidência em 30 dias.",
        "closure_criteria": "Contagem aprovada, ajustes lançados e causa documentada.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
    {
        "code": "sales.revenue_drop_review",
        "title": "Análise de queda de receita",
        "description": "Decompor a queda de receita por canal, categoria e horário.",
        "justification": "Queda persistente de receita exige ação antes de virar tendência.",
        "domain": "sales",
        "default_priority": 1,
        "suggested_role": "analyst",
        "suggested_deadline_days": 3,
        "preconditions": [],
        "steps": [
            "Comparar receita por canal e categoria com o período-base.",
            "Identificar os produtos que mais contribuíram para a queda.",
            "Verificar ruptura e preço dos produtos identificados.",
            "Propor ação corretiva por causa identificada.",
        ],
        "risk": "Conclusões precipitadas sem decomposição completa do escopo.",
        "expected_impact": "Causa da queda identificada e plano corretivo definido.",
        "tracking_kpi": "sales.net_revenue",
        "success_criteria": "Receita diária retorna à faixa do período-base em 14 dias.",
        "closure_criteria": "Causa documentada, ação executada e receita recuperada.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
    {
        "code": "sales.ticket_mix_review",
        "title": "Revisão de mix e ticket médio",
        "description": "Revisar mix de produtos e sugestões de venda para recuperar o ticket.",
        "justification": "Ticket médio em queda reduz receita mesmo com volume estável.",
        "domain": "sales",
        "default_priority": 3,
        "suggested_role": "analyst",
        "suggested_deadline_days": 7,
        "preconditions": [],
        "steps": [
            "Analisar itens por venda e preço médio por categoria.",
            "Identificar categorias com queda de participação.",
            "Revisar exposição e sugestão de venda casada no PDV.",
            "Acompanhar o ticket médio semanalmente.",
        ],
        "risk": "Ações comerciais podem pressionar margem se mal calibradas.",
        "expected_impact": "Recuperação do ticket médio sem perda de volume.",
        "tracking_kpi": "sales.average_ticket",
        "success_criteria": "Ticket médio recupera o nível do período-base em 30 dias.",
        "closure_criteria": "Ticket estabilizado e ações comerciais incorporadas à rotina.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
    {
        "code": "sales.return_rate_investigation",
        "title": "Investigação de devoluções",
        "description": "Investigar produtos e motivos por trás da alta de devoluções.",
        "justification": "Devoluções acima do padrão indicam problema de produto ou processo.",
        "domain": "sales",
        "default_priority": 2,
        "suggested_role": "branch_manager",
        "suggested_deadline_days": 5,
        "preconditions": [],
        "steps": [
            "Agrupar devoluções por produto, motivo e operador.",
            "Verificar lotes e validade dos produtos devolvidos.",
            "Revisar orientação de venda dos produtos mais devolvidos.",
            "Encaminhar não conformidades ao fornecedor quando aplicável.",
        ],
        "risk": "Tratamento sintomático sem atacar a causa raiz.",
        "expected_impact": "Taxa de devolução de volta ao padrão histórico.",
        "tracking_kpi": "sales.return_rate",
        "success_criteria": "Taxa de devolução abaixo do limite de alerta por 30 dias.",
        "closure_criteria": "Causa raiz tratada e taxa estabilizada no padrão.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
    {
        "code": "sales.cancellation_process_review",
        "title": "Revisão do processo de cancelamentos",
        "description": "Revisar cancelamentos de venda por motivo e por operador.",
        "justification": "Cancelamentos elevados indicam falha de processo, preço ou fraude.",
        "domain": "sales",
        "default_priority": 3,
        "suggested_role": "branch_manager",
        "suggested_deadline_days": 5,
        "preconditions": [],
        "steps": [
            "Listar cancelamentos por motivo, operador e horário.",
            "Conferir autorização e senha de cancelamento.",
            "Reforçar treinamento do processo de venda.",
            "Reportar padrões suspeitos à auditoria interna.",
        ],
        "risk": "Exposição de dados de operadores exige tratamento confidencial.",
        "expected_impact": "Redução de cancelamentos evitáveis e perdas associadas.",
        "tracking_kpi": "sales.cancellation_rate",
        "success_criteria": "Taxa de cancelamento dentro do limite por 30 dias.",
        "closure_criteria": "Processo revisado e taxa de cancelamento normalizada.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
    {
        "code": "sales.hourly_staffing_review",
        "title": "Revisão de escala por horário de pico",
        "description": "Ajustar escala de atendimento aos horários de maior venda por hora.",
        "justification": "Filas em horário de pico derrubam conversão e venda média por hora.",
        "domain": "sales",
        "default_priority": 4,
        "suggested_role": "branch_manager",
        "suggested_deadline_days": 10,
        "preconditions": [],
        "steps": [
            "Mapear venda média por hora dos últimos 60 dias.",
            "Cruzar com a escala atual de atendentes.",
            "Remanejar horários para cobrir os picos.",
            "Medir venda por hora após o ajuste.",
        ],
        "risk": "Aumento de custo de pessoal se o remanejo não for líquido-zero.",
        "expected_impact": "Aumento da venda por hora nos períodos de pico.",
        "tracking_kpi": "sales.hourly_average",
        "success_criteria": "Venda por hora nos picos cresce sem aumento de custo de escala.",
        "closure_criteria": "Escala ajustada e venda por hora estabilizada em patamar superior.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
    {
        "code": "margin.price_review",
        "title": "Revisão de preço de venda",
        "description": "Revisar preços de produtos com margem abaixo do piso da categoria.",
        "justification": "Preço desalinhado de custo corrói margem de forma silenciosa.",
        "domain": "margin",
        "default_priority": 2,
        "suggested_role": "company_admin",
        "suggested_deadline_days": 5,
        "preconditions": [],
        "steps": [
            "Listar produtos com margem abaixo do piso.",
            "Conferir custo atual e tributação de cada item.",
            "Simular novo preço e impacto na margem.",
            "Submeter o reajuste ao responsável autorizado e registrar a decisão antes de "
            "comunicar filiais.",
        ],
        "risk": "Reajuste pode reduzir competitividade em itens sensíveis a preço.",
        "expected_impact": "Margem bruta dos itens revisados de volta ao piso.",
        "tracking_kpi": "margin.gross_percent",
        "success_criteria": "Margem bruta da categoria acima do piso por 30 dias.",
        "closure_criteria": "Preços atualizados e margem estabilizada acima do piso.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
    {
        "code": "margin.discount_policy_review",
        "title": "Revisão da política de descontos",
        "description": "Revisar limites e alçadas de desconto após alta da taxa de desconto.",
        "justification": "Desconto acima da política transfere margem sem ganho de volume.",
        "domain": "margin",
        "default_priority": 2,
        "suggested_role": "company_admin",
        "suggested_deadline_days": 5,
        "preconditions": [],
        "steps": [
            "Analisar descontos por operador, categoria e campanha.",
            "Comparar taxa praticada com o limite da política.",
            "Propor ajustes de alçadas e bloqueios no PDV para aprovação do responsável "
            "autorizado.",
            "Comunicar a nova política às equipes.",
        ],
        "risk": "Restrição excessiva pode derrubar conversão de vendas.",
        "expected_impact": "Taxa de desconto de volta ao teto sem perda de receita.",
        "tracking_kpi": "sales.discount_rate",
        "success_criteria": "Taxa de desconto dentro do teto por 30 dias.",
        "closure_criteria": "Política ajustada, alçadas configuradas e taxa normalizada.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
    {
        "code": "margin.negative_margin_cleanup",
        "title": "Saneamento de margem negativa",
        "description": "Corrigir produtos vendidos com margem negativa.",
        "justification": "Venda abaixo do custo gera prejuízo direto em cada unidade vendida.",
        "domain": "margin",
        "default_priority": 1,
        "suggested_role": "company_admin",
        "suggested_deadline_days": 3,
        "preconditions": [],
        "steps": [
            "Listar produtos com margem negativa no período.",
            "Verificar custo, tributo e preço cadastrados.",
            "Preparar correção cadastral ou proposta de reajuste e submetê-la à aprovação humana.",
            "Auditar vendas realizadas enquanto o erro vigorou.",
        ],
        "risk": "Correção de preço pode gerar atrito com clientes recorrentes.",
        "expected_impact": "Eliminação das vendas com margem negativa.",
        "tracking_kpi": "margin.negative_margin_rate",
        "success_criteria": "Taxa de produtos com margem negativa zerada por 14 dias.",
        "closure_criteria": "Cadastros corrigidos e nenhuma venda abaixo do custo.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
    {
        "code": "margin.gmroi_rebalance",
        "title": "Rebalanceamento de capital por GMROI",
        "description": "Realocar capital de itens de baixo GMROI para itens de alto retorno.",
        "justification": "Capital em itens de baixo GMROI reduz o retorno total do estoque.",
        "domain": "margin",
        "default_priority": 3,
        "suggested_role": "analyst",
        "suggested_deadline_days": 10,
        "preconditions": [],
        "steps": [
            "Classificar produtos por GMROI na categoria.",
            "Propor redução de pedidos dos itens de baixo retorno para aprovação no processo de "
            "compras.",
            "Ampliar cobertura dos itens de alto retorno.",
            "Acompanhar GMROI da categoria mensalmente.",
        ],
        "risk": "Redução de sortimento pode afetar a percepção de variedade.",
        "expected_impact": "Aumento do retorno sobre o capital em estoque.",
        "tracking_kpi": "margin.gmroi",
        "success_criteria": "GMROI da categoria cresce em relação ao trimestre anterior.",
        "closure_criteria": "Carteira rebalanceada e GMROI em trajetória de alta.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
    {
        "code": "margin.price_dispersion_review",
        "title": "Revisão de dispersão de preços",
        "description": "Padronizar preços entre filiais com dispersão acima do tolerado.",
        "justification": "Dispersão de preço entre filiais confunde o cliente e corrói margem.",
        "domain": "margin",
        "default_priority": 4,
        "suggested_role": "analyst",
        "suggested_deadline_days": 10,
        "preconditions": [],
        "steps": [
            "Comparar preço dos mesmos produtos entre filiais.",
            "Identificar origem da divergência (custo, campanha, cadastro).",
            "Definir preço de referência e alinhar exceções justificadas.",
            "Monitorar dispersão após o alinhamento.",
        ],
        "risk": "Alinhamento cego pode ignorar diferenças regionais de custo.",
        "expected_impact": "Dispersão de preços dentro da banda tolerada.",
        "tracking_kpi": "margin.price_dispersion",
        "success_criteria": "Dispersão abaixo do limite definido por 30 dias.",
        "closure_criteria": "Preços alinhados ou exceções formalmente justificadas.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
    {
        "code": "purchases.order_parameter_review",
        "title": "Revisão de parâmetros de compra",
        "description": "Revisar múltiplos, lotes mínimos e sugestões automáticas de compra.",
        "justification": "Parâmetros desatualizados geram excesso, ruptura e compra emergencial.",
        "domain": "purchases",
        "default_priority": 2,
        "suggested_role": "analyst",
        "suggested_deadline_days": 5,
        "preconditions": [],
        "steps": [
            "Auditar múltiplos e lotes mínimos dos principais fornecedores.",
            "Confrontar sugestão automática com demanda real.",
            "Corrigir parâmetros divergentes.",
            "Acompanhar aderência ao múltiplo nas próximas compras.",
        ],
        "risk": "Correções podem exigir renegociação de condições comerciais.",
        "expected_impact": "Compras aderentes aos parâmetros e sem emergenciais.",
        "tracking_kpi": "purchases.multiple_adherence",
        "success_criteria": "Aderência ao múltiplo acima da meta por 30 dias.",
        "closure_criteria": "Parâmetros corrigidos e aderência estabilizada na meta.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
    {
        "code": "purchases.emergency_rate_reduction",
        "title": "Redução de compras emergenciais",
        "description": "Atacar as causas das compras emergenciais recorrentes.",
        "justification": "Compra emergencial tem custo maior e indica falha de planejamento.",
        "domain": "purchases",
        "default_priority": 2,
        "suggested_role": "analyst",
        "suggested_deadline_days": 7,
        "preconditions": [],
        "steps": [
            "Listar compras emergenciais por produto e motivo.",
            "Corrigir ponto de pedido dos itens recorrentes.",
            "Revisar lead time dos fornecedores envolvidos.",
            "Medir a taxa de emergenciais no ciclo seguinte.",
        ],
        "risk": "Aumento de estoque de segurança eleva capital imobilizado.",
        "expected_impact": "Taxa de compras emergenciais de volta ao padrão.",
        "tracking_kpi": "purchases.emergency_rate",
        "success_criteria": "Taxa de emergenciais abaixo do limite por 30 dias.",
        "closure_criteria": "Causas tratadas e taxa de emergenciais normalizada.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
    {
        "code": "purchases.receipt_followup",
        "title": "Cobrança de recebimento de pedidos",
        "description": "Cobrar fornecedores de pedidos vencidos ou com entrega parcial.",
        "justification": "Pedidos sem recebimento comprometem cobertura e geram ruptura.",
        "domain": "purchases",
        "default_priority": 2,
        "suggested_role": "branch_manager",
        "suggested_deadline_days": 3,
        "preconditions": [],
        "steps": [
            "Listar pedidos vencidos e entregas parciais.",
            "Acionar os fornecedores com prazo de regularização.",
            "Recomendar reprogramação ou cancelamento para decisão do responsável autorizado.",
            "Avaliar fornecedor reincidente para renegociação.",
        ],
        "risk": "Cancelamento pode deixar lacuna de cobertura temporária.",
        "expected_impact": "Taxa de recebimento de pedidos de volta à meta.",
        "tracking_kpi": "purchases.receipt_rate",
        "success_criteria": "Pedidos vencidos zerados e taxa de recebimento na meta.",
        "closure_criteria": "Carteira de pedidos regularizada sem vencidos.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
    {
        "code": "purchases.freight_review",
        "title": "Revisão de condições de frete",
        "description": "Renegociar fretes com taxa acima da referência da rede.",
        "justification": "Frete acima da referência reduz a margem de compra.",
        "domain": "purchases",
        "default_priority": 4,
        "suggested_role": "company_admin",
        "suggested_deadline_days": 15,
        "preconditions": [],
        "steps": [
            "Comparar taxa de frete por fornecedor e rota.",
            "Levantar referências de mercado para as rotas.",
            "Renegociar com os fornecedores acima da referência.",
            "Registrar novas condições no cadastro.",
        ],
        "risk": "Renegociação pode alongar prazos de entrega.",
        "expected_impact": "Redução da taxa média de frete sobre compras.",
        "tracking_kpi": "purchases.freight_rate",
        "success_criteria": "Taxa de frete média dentro da referência em 60 dias.",
        "closure_criteria": "Condições renegociadas e taxa estabilizada na referência.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
    {
        "code": "purchases.return_process_review",
        "title": "Revisão de devoluções a fornecedores",
        "description": "Formalizar devoluções de compra pendentes de coleta ou crédito.",
        "justification": "Devolução sem baixa financeira gera crédito não recebido.",
        "domain": "purchases",
        "default_priority": 3,
        "suggested_role": "analyst",
        "suggested_deadline_days": 7,
        "preconditions": [],
        "steps": [
            "Listar devoluções pendentes de coleta ou crédito.",
            "Acionar fornecedores para agendamento de coleta.",
            "Conferir créditos recebidos contra notas de devolução.",
            "Preparar a baixa sistêmica documentada e submetê-la ao responsável autorizado.",
        ],
        "risk": "Demora do fornecedor pode exigir compensação em pagamento.",
        "expected_impact": "Créditos de devolução recebidos e baixados.",
        "tracking_kpi": "purchases.return_rate",
        "success_criteria": "Nenhuma devolução pendente há mais de 15 dias.",
        "closure_criteria": "Pendências zeradas e créditos conciliados.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
    {
        "code": "suppliers.renegotiation",
        "title": "Renegociação com fornecedor",
        "description": "Renegociar custo e condições com fornecedor com variação acima do teto.",
        "justification": "Variação de custo acima do teto corrói margem de toda a categoria.",
        "domain": "suppliers",
        "default_priority": 2,
        "suggested_role": "company_admin",
        "suggested_deadline_days": 15,
        "preconditions": [],
        "steps": [
            "Levantar histórico de custo e volume do fornecedor.",
            "Preparar comparativo com fornecedores alternativos.",
            "Conduzir renegociação de tabela e prazos.",
            "Formalizar novas condições e atualizar cadastro.",
        ],
        "risk": "Risco de desabastecimento se a negociação travar.",
        "expected_impact": "Variação de custo de volta ao teto acordado.",
        "tracking_kpi": "suppliers.cost_variation",
        "success_criteria": "Variação de custo dentro do teto no próximo ciclo.",
        "closure_criteria": "Acordo formalizado e custo estabilizado no teto.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
    {
        "code": "suppliers.lead_time_review",
        "title": "Revisão de lead time de fornecedor",
        "description": "Recalibrar lead time cadastrado com base nas entregas recentes.",
        "justification": "Lead time desatualizado distorce ponto de pedido e cobertura.",
        "domain": "suppliers",
        "default_priority": 3,
        "suggested_role": "analyst",
        "suggested_deadline_days": 10,
        "preconditions": [],
        "steps": [
            "Calcular lead time realizado dos últimos recebimentos.",
            "Comparar com o lead time cadastrado.",
            "Atualizar cadastro e recalcular pontos de pedido.",
            "Cobrar plano de melhoria dos fornecedores fora do padrão.",
        ],
        "risk": "Lead time maior eleva estoque de segurança necessário.",
        "expected_impact": "Parâmetros logísticos alinhados à realidade de entrega.",
        "tracking_kpi": "suppliers.average_lead_time",
        "success_criteria": "Lead time cadastrado com desvio menor que 20% do realizado.",
        "closure_criteria": "Cadastros atualizados e desvios dentro do tolerado.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
    {
        "code": "suppliers.fill_rate_action",
        "title": "Plano de atendimento de fornecedor",
        "description": "Exigir plano de melhoria de fornecedor com atendimento abaixo da meta.",
        "justification": "Baixa taxa de atendimento transfere ruptura para a loja.",
        "domain": "suppliers",
        "default_priority": 2,
        "suggested_role": "company_admin",
        "suggested_deadline_days": 10,
        "preconditions": [],
        "steps": [
            "Quantificar faltas por produto e por pedido.",
            "Reunião de cobrança com plano de ação do fornecedor.",
            "Avaliar dual sourcing para itens críticos.",
            "Monitorar atendimento nos próximos ciclos.",
        ],
        "risk": "Dual sourcing pode reduzir poder de negociação por volume.",
        "expected_impact": "Taxa de atendimento do fornecedor de volta à meta.",
        "tracking_kpi": "suppliers.fill_rate",
        "success_criteria": "Atendimento acima da meta por dois ciclos consecutivos.",
        "closure_criteria": "Plano cumprido e atendimento estabilizado na meta.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
    {
        "code": "suppliers.dependency_reduction",
        "title": "Redução de dependência de fornecedor",
        "description": "Desenvolver alternativas para categorias dependentes de um fornecedor.",
        "justification": "Dependência concentrada amplifica impacto de qualquer falha.",
        "domain": "suppliers",
        "default_priority": 3,
        "suggested_role": "company_admin",
        "suggested_deadline_days": 30,
        "preconditions": [],
        "steps": [
            "Mapear categorias com concentração acima do limite.",
            "Homologar fornecedores alternativos.",
            "Distribuir volume gradualmente entre os homologados.",
            "Revisar concentração trimestralmente.",
        ],
        "risk": "Perda de escala pode elevar custo unitário.",
        "expected_impact": "Concentração de abastecimento dentro do limite de risco.",
        "tracking_kpi": "suppliers.dependency",
        "success_criteria": "Dependência do principal fornecedor abaixo do limite.",
        "closure_criteria": "Alternativas homologadas e concentração dentro do limite.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
    {
        "code": "suppliers.quality_claim",
        "title": "Reclamação formal de qualidade",
        "description": "Abrir reclamação formal por falhas de qualidade no recebimento.",
        "justification": "Falhas de qualidade geram perda, devolução e risco ao cliente.",
        "domain": "suppliers",
        "default_priority": 2,
        "suggested_role": "company_admin",
        "suggested_deadline_days": 7,
        "preconditions": [],
        "steps": [
            "Consolidar evidências das falhas por lote e nota.",
            "Abrir reclamação formal com prazo de resposta.",
            "Solicitar proposta de crédito ou reposição, sem aceitar compromisso financeiro "
            "automaticamente.",
            "Acompanhar score de qualidade do fornecedor.",
        ],
        "risk": "Escalada pode deteriorar relacionamento comercial.",
        "expected_impact": "Qualidade do fornecimento de volta ao padrão acordado.",
        "tracking_kpi": "suppliers.quality_score",
        "success_criteria": "Score de qualidade acima da meta nos próximos recebimentos.",
        "closure_criteria": "Reclamação respondida, crédito recebido e score recuperado.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
    {
        "code": "operations.integration_check",
        "title": "Verificação de integração de dados",
        "description": "Diagnosticar e restabelecer integrações com falha ou atraso.",
        "justification": "Sem integração atualizada, KPIs e diagnósticos perdem validade.",
        "domain": "operations",
        "default_priority": 1,
        "suggested_role": "tenant_admin",
        "suggested_deadline_days": 1,
        "preconditions": [],
        "steps": [
            "Identificar lotes com falha e origem do erro.",
            "Corrigir credencial, conexão ou layout conforme a causa.",
            "Reprocessar os lotes afetados.",
            "Confirmar freshness dentro do SLA.",
        ],
        "risk": "Reprocessamento incorreto pode duplicar registros.",
        "expected_impact": "Disponibilidade da integração de volta ao SLA.",
        "tracking_kpi": "operations.integration_availability",
        "success_criteria": "Disponibilidade acima do SLA por 7 dias.",
        "closure_criteria": "Integrações estáveis e freshness dentro do SLA.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
    {
        "code": "operations.rejection_triage",
        "title": "Tratamento de rejeições de importação",
        "description": "Classificar e corrigir registros rejeitados na importação.",
        "justification": "Rejeições elevadas reduzem a completude dos dados analíticos.",
        "domain": "operations",
        "default_priority": 2,
        "suggested_role": "analyst",
        "suggested_deadline_days": 3,
        "preconditions": [],
        "steps": [
            "Agrupar rejeições por motivo e arquivo de origem.",
            "Corrigir cadastros ou layouts causadores.",
            "Reenviar registros corrigidos.",
            "Acompanhar taxa de rejeição na próxima carga.",
        ],
        "risk": "Correções manuais em massa podem introduzir novos erros.",
        "expected_impact": "Completude de volta à meta de qualidade.",
        "tracking_kpi": "operations.rejection_rate",
        "success_criteria": "Taxa de rejeição abaixo do limite na próxima carga.",
        "closure_criteria": "Causas corrigidas e rejeições dentro do limite.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
    {
        "code": "operations.duplicate_cleanup",
        "title": "Saneamento de duplicidades",
        "description": "Investigar e eliminar registros duplicados na ingestão.",
        "justification": "Duplicidades inflam medidas e corrompem KPIs e diagnósticos.",
        "domain": "operations",
        "default_priority": 2,
        "suggested_role": "analyst",
        "suggested_deadline_days": 5,
        "preconditions": [],
        "steps": [
            "Identificar origem das duplicidades por chave natural.",
            "Corrigir o processo de ingestão causador.",
            "Deduplicar os registros afetados com rastreabilidade.",
            "Validar KPIs impactados após o saneamento.",
        ],
        "risk": "Deduplicação incorreta pode remover registros legítimos.",
        "expected_impact": "Taxa de duplicidade de volta ao limite de qualidade.",
        "tracking_kpi": "operations.duplicate_rate",
        "success_criteria": "Taxa de duplicidade abaixo do limite por 7 dias.",
        "closure_criteria": "Causa corrigida, registros saneados e KPIs validados.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
    {
        "code": "operations.freshness_recovery",
        "title": "Recuperação de freshness analítica",
        "description": "Restabelecer a atualização analítica dentro do SLA de freshness.",
        "justification": "Dados desatualizados invalidam sinais e diagnósticos recentes.",
        "domain": "operations",
        "default_priority": 2,
        "suggested_role": "tenant_admin",
        "suggested_deadline_days": 2,
        "preconditions": [],
        "steps": [
            "Verificar fila de atualização e jobs com falha.",
            "Reexecutar atualizações pendentes em ordem de prioridade.",
            "Investigar gargalos de processamento recorrentes.",
            "Confirmar watermark e freshness atualizados.",
        ],
        "risk": "Reprocessamento concorrente pode pressionar o banco.",
        "expected_impact": "Freshness dentro do SLA e pipeline estável.",
        "tracking_kpi": "operations.data_freshness",
        "success_criteria": "Freshness dentro do SLA por 7 dias consecutivos.",
        "closure_criteria": "Pipeline estável e freshness sustentada no SLA.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
    {
        "code": "operations.quality_incident_review",
        "title": "Revisão de incidentes de qualidade",
        "description": "Analisar incidentes de qualidade recorrentes e corrigir a causa.",
        "justification": "Incidentes recorrentes indicam falha estrutural no pipeline.",
        "domain": "operations",
        "default_priority": 3,
        "suggested_role": "analyst",
        "suggested_deadline_days": 7,
        "preconditions": [],
        "steps": [
            "Consolidar incidentes por tipo e origem.",
            "Priorizar a causa com maior impacto em completude.",
            "Corrigir regra de validação ou rotina de carga.",
            "Monitorar reincidência após a correção.",
        ],
        "risk": "Correção de regras pode rejeitar registros antes aceitos.",
        "expected_impact": "Redução sustentada dos incidentes de qualidade.",
        "tracking_kpi": "operations.quality_incidents",
        "success_criteria": "Sem reincidência do incidente tratado por 30 dias.",
        "closure_criteria": "Causa corrigida e incidentes dentro do padrão.",
        "status": "active",
        "version": 1,
        "execution_mode": "human_review_required",
        "allows_automatic_financial_execution": False,
        "safety_constraints": [
            "A recomendação é consultiva e exige revisão e autorização humana antes da execução.",
            "Nenhuma compra, pagamento, crédito, baixa, alteração de preço ou "
            "compromisso financeiro é executado automaticamente.",
        ],
    },
)


def canonical_json(value: object) -> str:
    """Serialize migration data using the frozen canonical JSON contract."""

    return json.dumps(value, **CANONICAL_JSON_OPTIONS)  # type: ignore[arg-type]


def deterministic_hash(value: object) -> str:
    """Return the SHA-256 hex digest of the canonical UTF-8 JSON payload."""

    return sha256(canonical_json(value).encode("utf-8")).hexdigest()


SNAPSHOT_ID = uuid5(
    NAMESPACE_URL,
    f"pharma-intelligence:diagnostic-action-catalog:snapshot:{CATALOG_VERSION}",
)
CATALOG_HASH = deterministic_hash(ACTION_CATALOG_DEFINITIONS)
ACTION_COUNT = len(ACTION_CATALOG_DEFINITIONS)


def entry_id(action_code: str, action_version: int) -> UUID:
    """Return the stable ID for one action version inside this snapshot."""

    return uuid5(
        NAMESPACE_URL,
        "pharma-intelligence:diagnostic-action-catalog:"
        f"snapshot:{CATALOG_VERSION}:{action_code}:v{action_version}",
    )


def iter_entry_rows() -> Iterator[dict[str, Any]]:
    """Yield database rows in the catalog's stable tuple order."""

    for definition in ACTION_CATALOG_DEFINITIONS:
        action_code = str(definition["code"])
        action_version = cast(int, definition["version"])
        yield {
            "id": entry_id(action_code, action_version),
            "catalog_snapshot_id": SNAPSHOT_ID,
            "action_code": action_code,
            "action_version": action_version,
            "title": str(definition["title"]),
            "domain": str(definition["domain"]),
            "default_priority": cast(int, definition["default_priority"]),
            "status": str(definition["status"]),
            "definition_snapshot": dict(definition),
            "definition_hash": deterministic_hash(definition),
            "execution_mode": str(definition["execution_mode"]),
            "requires_human_review": True,
        }
